(()=>{
  let credentials=null;
  const status=document.querySelector('#manage-result'),actions=document.querySelector('#manage-actions'),summary=document.querySelector('#appointment-summary');
  const dateInput=document.querySelector('#reschedule-date'),timeSelect=document.querySelector('#reschedule-time');
  const message=(text,bad=false)=>{status.textContent=text;status.className='form-status '+(bad?'error':'success')};
  const localTime=iso=>new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso));
  const localDate=date=>date.toLocaleDateString('en-CA',{timeZone:'America/Mexico_City'});
  if(dateInput){dateInput.min=localDate(new Date());const max=new Date();max.setMonth(max.getMonth()+4);dateInput.max=localDate(max)}
  document.querySelector('#lookup-form').addEventListener('submit',async event=>{event.preventDefault();credentials=Object.fromEntries(new FormData(event.currentTarget));message('Buscando…');try{const response=await fetch('/api/appointments?folio='+encodeURIComponent(credentials.folio)+'&email='+encodeURIComponent(credentials.email)),data=await response.json();if(!response.ok)throw new Error(data.error);const appointment=data.appointment;summary.innerHTML='<strong>'+appointment.service_name+'</strong><br>'+appointment.date+' · '+localTime(appointment.start_at)+'<br>Estado: '+appointment.status;actions.hidden=!data.canChange;message(data.canChange?'Puedes cancelar o elegir una nueva fecha.':'Los cambios en línea cierran 24 horas antes; contáctanos si necesitas ayuda.')}catch(error){actions.hidden=true;message(error.message,true)}});
  dateInput?.addEventListener('change',async()=>{timeSelect.disabled=true;timeSelect.innerHTML='<option value="">Consultando…</option>';try{const query=new URLSearchParams({...credentials,date:dateInput.value}),response=await fetch('/api/appointments?'+query),data=await response.json();if(!response.ok)throw new Error(data.error);timeSelect.innerHTML=data.slots?.length?'<option value="">Selecciona</option>'+data.slots.map(time=>`<option>${time}</option>`).join(''):'<option value="">Sin horarios disponibles</option>';timeSelect.disabled=!data.slots?.length}catch(error){timeSelect.innerHTML='<option value="">No disponible</option>';message(error.message,true)}});
  document.querySelector('#reschedule-form').addEventListener('submit',async event=>{event.preventDefault();await send({...credentials,...Object.fromEntries(new FormData(event.currentTarget)),action:'reschedule'})});
  document.querySelector('#cancel-booking').addEventListener('click',async()=>{if(confirm('¿Confirmas que deseas cancelar esta cita?'))await send({...credentials,action:'cancel'})});
  async function send(data){message('Procesando…');try{const response=await fetch('/api/appointments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),result=await response.json();if(!response.ok)throw new Error(result.error);actions.hidden=true;message(result.message)}catch(error){message(error.message,true)}}
})();
